
<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <RunAnalyzers>false</RunAnalyzers>
    <ImplicitUsings>enable</ImplicitUsings>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
    <Verify_SponsorshipExemption>OpenSource</Verify_SponsorshipExemption>
    <Verify_SponsorshipExemptionUntil>2027-08</Verify_SponsorshipExemptionUntil>
  </PropertyGroup>
</Project>