<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.WinForms" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Verify.Nunit" VersionOverride="33.0.1" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" VersionOverride="33.0.1" />
    <PackageReference Include="Verify.ImageMagick" />
    <ProjectReference Include="..\WinFormsApp\WinFormsApp.csproj" />
  </ItemGroup>
</Project>
