<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.ImageMagick" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Verify.Nunit" VersionOverride="33.0.0-beta.3" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" VersionOverride="33.0.0-beta.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Verify.Xaml" />
    <ProjectReference Include="..\WpfApp\WpfApp.csproj" />
  </ItemGroup>
</Project>
